content/en-us/chat/legacy/client-side-chat-modules.md

Corrected: rsult to result.
Corrected: cahgned to changed.

Fix spelling errors

---

content/en-us/ui/animation.md

Because strings are immutable, calling `gsub` without storing the result is not accomplishing anything. Additionally, there was no comment explaining what the `gsub` was doing. I fixed these issues, and also replaced `wait` with `task.wait` to adopt modern best practice.

Fix UI animation typewriter

---

content/en-us/characters/pathfinding.md

The code segment used to try to use the ModifierID property of a PathWaypoint. This property does not exist. I replaced it with the Label property. This is the correct property to find the ModifierID of a PathWaypoint.
You can view my forum post from May talking about this issue here: https://devforum.roblox.com/t/incorrect-pathfinding-modifier-documentationcant-post-there/2317981.

Replaced ModifierID with Label property

---

content/en-us/players/index.md

The current example tries to save the Data Store object instead of the player's data. This replaces the 2nd argument of the call to use the player's current data instead of the Data Store object.

Update SetAsync example to correctly use player data

---

content/en-us/workspace/raycasting.md

Corrects the maximum ray magnitude text from 5,000 to 15,000.
Source: https://devforum.roblox.com/t/upgraded-improved-and-faster-raycasts/1420368 and RaycastMaxDistance DFFlag value

Correct the maximum ray magnitude text

---

content/en-us/cloud-services/cross-server-messaging.md

Made an auto-link direct to their specific property information.

Fix auto-link in cross-server-messaging.md

---

content/en-us/cloud-services/memory-stores/queue.md
content/en-us/cloud-services/memory-stores/sorted-map.md

Added auto-links to pcall. observability.md might also have a missing auto-link but I did not modify it in case it was intentional.

Add auto-links to memory-stores

---

content/en-us/studio/instance-attributes.md

Super quick addition of Font as a supported type for instance attributes.

Add Font datatype to attributes supported list

---

content/en-us/production/localization/localizing-with-scripting.md

Removes two unused variables from the [Localizing with Scripting](https://create.roblox.com/docs/production/localization/localizing-with-scripting#creating-a-translationhelper-module) page. These appear to be left over from another function, and now only serve to confuse the reader. 

Remove unused variables

---

content/en-us/ui/drag-detectors.md

Replaced `Class.Ray` with `Datatype.Ray` as `Class.Ray` does not exist.

Fix auto-link in drag-detectors.md

---

content/en-us/reference/engine/classes/TouchTransmitter.yaml

[FilteringEnabled no longer exists](https://devforum.roblox.com/t/removal-of-experimental-mode/152807) so this doesn't make sense anymore.

Remove reference to FilteringEnabled in `TouchTransmitter.yml`

---

content/en-us/reference/engine/classes/UserInputService.yaml

ModalEnabled is correctly tagged as deprecated but does not have any texts pointing towards the alternative. This submission points developers to GuiService.TouchControlsEnabled which supersedes UserInputService.ModalEnabled.
[TouchControlsEnabled superseded ModalEnabled in Release 493](https://devforum.roblox.com/t/release-notes-for-493/1450062/5?u=colbert2677).

Add deprecation message for ModalEnabled

---

content/en-us/reference/engine/enums/KeyCode.yaml

Add correct key value for the `Enum.Keycode.KeypadDivide` member.

add correction to KeypadDivide member of the KeyCode enum

---

content/en-us/reference/engine/classes/AnimationTrack.yaml

Improved text overrides for auto-links by including "s".

Fix auto-links in AnimationTrack.yaml

---

content/en-us/reference/engine/classes/MarketplaceService.yaml

PromptProductPurchaseFinished had the deprecated tag added then removed but the description in the wiki still mentions it is deprecated

PromptProductPurchaseFinished is no longer deprecated

---

content/en-us/reference/engine/classes/UnreliableRemoteEvent.yaml

Add V1 description of UnreliableRemoteEvents. Note that much of this is the same as RemoteEvents and was ported over with minor changes. This is because this new instance is a variant of the RemoteEvent instance.
Essentially what I did was added how this instance differs from RemoteEvents + added the caveats that developers should be aware of when using UREs.
https://devforum.roblox.com/t/introducing-unreliableremoteevents/2724155

CLI-88769 - Add API documentation for UnreliableRemoteEvents

---

content/en-us/reference/engine/classes/EditableMesh.yaml

Adds the limits for triangles and verticies on EditableMesh. (Source is me testing this by bruteforcing `AddVertex` and `AddTriangle`)

Add tri/vertex limits to EditableMesh

---

content/en-us/reference/engine/globals/LuaGlobals.yaml

Correct the description of the unpack parameters.
The description of `unpack`'s `j` parameter was wrong. It is not a count, it is the index of the last element to `unpack`. Updated the description of the `i` parameter to match the new wording of the `j` parameter.

Correct description of global unpack's parameters

---

content/en-us/reference/engine/classes/WorldRoot.yaml

Corrects the maximum ray distance text in a method description. Also adds maximum shapecast size and distance info to method parameter summaries.
Sources: https://devforum.roblox.com/t/upgraded-improved-and-faster-raycasts/1420368, https://devforum.roblox.com/t/introducing-shapecasts/2320655, and RaycastMaxDistance DFFlag value.

Add more ray info

---

content/en-us/reference/engine/classes/PackageLink.yaml

Minor grammatical issue, you forgot to add "are" in the sentence "They **are** not creatable through `Class.Script|scripts`."

Update PackageLink.yaml - minor issue

---

content/en-us/reference/engine/classes/TextChatService.yaml

This attempts to fix the markdown formatting for the CreateDefaultCommands in `TextChatService.yaml`. I say this because I'm unsure of whether this fixes the markdown issue or not since I cannot seem to test it.
I believe the markdown was written wrong because of `Class.TextChannel | TextChannels`
This is what it looks like right now on the docs:

Fix markdown for CreateDefaultCommands in TextChatService.yaml

---

content/en-us/reference/engine/classes/TextChatService.yaml

The last pull request for this problem fixed most of the problem, but it looks like the bar character in `Class.TextChannel | TextChannels` is now being used for the markdown table. 
This is the reason why this pull request adds an escape character before the bar. It is unknown if this will break the automatic link:
`Class.TextChannel \| TextChannels`
I tried to see what was done in such a scenario on other pages, but I was unable to find a similar scenario. The closest I found was this table on [Datatype.Vector3](https://create.roblox.com/docs/reference/engine/datatypes/Vector3) However, it turned out that table just used pure html tags for its table and it doesn't override the default text link. 

Add markdown escape to TextChatService.yaml

---

content/en-us/reference/engine/classes/WorldRoot.yaml

Sphere cast documentation previously stated that:
"This method throws an error if it is passed invalid CFrame, size, or direction inputs."
However a sphere cast doesn't take in a CFrame or size value.
I've updated this to be "radius or direction".

Update Spherecast error cases in WorldRoot.yaml

---

content/en-us/unity.md

This fixes a typo by changing `Script.parent` to `script.Parent`. 

Fix a typo in a sample script in unity.md

---

content/en-us/reference/engine/classes/Instance.yaml

Added 100 character limit information to instance.Name. Obtained information from Roblox Studio, where setting the property to longer string truncates it to 100.

Add Instance.Name size limit

---

content/en-us/reference/engine/classes/Instance.yaml

`Instance:Clone()` will return `nil` if it has `Instance.Archivable` set to `false`, so the correct type is `Instance?`
Edit: Since we apparently cannot directly edit type fields, I added a note to the description that describes this particular case.

Corrected :Clone() return type

---

content/en-us/reference/engine/classes/VRService.yaml

The `VRService:RecenterUserHeadCFrame()` states that it is [_similar_](https://create.roblox.com/docs/reference/engine/classes/VRService#RecenterUserHeadCFrame) to `UserInputService:ReenterUserHeadCFrame()`, whereas the `UserInputService` version states that it is [_identical_](https://create.roblox.com/docs/reference/engine/classes/UserInputService#RecenterUserHeadCFrame) to the other. This is an important language distinction, as similarity does not communicate that they are identical.
This PR changes the `VRService` version language to also state that it is identical, not just similar.

Parity between VRService and UserInputService `RecenterUserHeadCFrame` methods

---

content/en-us/reference/engine/libraries/os.yaml

Changes the os.date()  "%c" specifier example to reflect the actual output of it

Changed os.date() "%c" specifier example format to actual output

---

content/en-us/reference/engine/classes/TextChatService.yaml

* Add needed closing backtick on return value
Added a backtick to the return value to allow for documentation linking and prevention against weird formatting errors like this:

fix: patch formatting on TextChatService.OnBubbleDisplay

---

content/en-us/reference/engine/classes/TweenBase.yaml

Addressing https://roblox.atlassian.net/browse/CLICONTENT-4604 - adding more info to Pause()
Addressing the DevForum bug https://roblox.atlassian.net/browse/CLICONTENT-4604 - adding more info to Pause() in TweenBase to make sure Devs don't expect Pause to work unless the Tween is playing.

Update the Pause() docs in TweenBase

---

content/en-us/tutorials/fundamentals/coding-4/glow-lights-with-for-loops.md

Replaced `Light.Brightness = brightnessChange` to `Light.Brightness = currentBrightness`, because the former is incorrect and diverges from the code written below on line 75 of the tutorial, thus possibly leading to confusion/mistake.

fix: Change incorrect assignment of variable on line 71

---

content/en-us/education/build-it-play-it-story-games/code-the-story.md
content/en-us/reference/engine/classes/AvatarEditorService.yaml
content/en-us/reference/engine/classes/HumanoidDescription.yaml
content/en-us/reference/engine/classes/Tool.yaml

A few pages have broken backtick syntax for in-line code samples. For example, they begin and end with four ` instead of three. Additionally, before the closing backticks, there is a duplicate set of three backticks followed by a period or quote. This duplicate set leaks markdown syntax into the code sample, as shown in this screenshot at the bottom:

Fix broken backticks in in-line code samples

---

content/en-us/cloud/reference/oauth2.md

Following up on https://github.com/Roblox/creator-docs/pull/164
Made refresh token bullet points consistent with Access token bullet points for easier comparison.

Make refresh token bullets consistent with Access token bullets

---

content/en-us/reference/engine/classes/ScrollingFrame.yaml

This PR updates the descriptions for the ScrollingFrame.AutomaticCanvasSize and ScrollingFrame.AbsoluteCanvasSize property to be more descriptive. The prior descriptions were definitely causing confusion as evidenced by several dev forum threads and me personally running into the issue as well.
Please see comments in https://roblox.atlassian.net/browse/UISYS-1976 
- [x ] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [x ] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [x ] To …

Fix ScrollingFrame descriptions around ScrollingFrame.AutomaticCanvasSize

---

content/en-us/luau/userdata.md

Arbitrary C/C++ data that exist<ins>s</ins> in Luau.
the page description got it right, the page content didn't
- fix typo on the [userdata](https://create.roblox.com/docs/luau/userdata) page

Fix typo in userdata data type

---

content/en-us/reference/engine/classes/Status.yaml

Fixes a small typo where it says "depreciated" instead of "deprecated"

fix typo in "deprecated"

---

content/en-us/production/publishing/selling-on-the-creator-store.md

The links should point to:
https://create.roblox.com/settings/eligibility/priced-assets to check seller onboarding status
Currently, the link that is set will 404, as it does not exist.

Update selling-on-the-creator-store.md Seller Onboarding Links

---

content/en-us/reference/engine/classes/ChangeHistoryService.yaml

Adds information about a previously-undocumented failure condition to the `ChangeHistory:TryBeginRecording()` documentation.

Clarify TryBeginRecording fails in Run/Play mode

---

content/en-us/reference/engine/classes/Mouse.yaml

In the Mouse class documentation I changed the piece of code `mouse.Hit.p` to `mouse.Hit.Position` since CFrame.p is less understandable than `mouse.Hit.Position`

Changed mouse.Hit.p to mouse.Hit.Position

---

content/en-us/reference/engine/classes/LocalizationService.yaml

I have changed the mention of Turkey to Türkiye following the name change from the UN
To allow for better site crawling I put put turkey in brackets
https://globalnews.ca/news/8892204/turkey-renamed-turkiye-united-nations/

Update LocalizationService.yaml from Turkey to Republic of Türkiye

---

content/en-us/luau/luau-csharp-comparison.md

- Replaces the legacy approximate Luau conditional operators following the `a and b or c` syntax, with modern if-then-else expresions following the `if a then b or c` syntax.
- This change is supported by the Luau syntax docs stating that if-then-else expressions are now preferred over the standard Lua idiom of using the `a and b or c` syntax - https://luau-lang.org/syntax#if-then-else-expressions

Replace legacy approximate Luau conditional operator

---

content/en-us/reference/engine/enums/Material.yaml

Updated multiple materials summary's regarding if they work on 'BasePart' and 'Terrain', as most of them now work on 'BasePart' as-well.
Changed summary on multiple materials that were previously marked as "Applies to 'Class.Terrain' only." to "Applies to 'Class.BasePart' and 'Class.Terrain'." as these materials now work on both.

Enum.Materials summary updated what classes they work on.

---

content/en-us/cloud-services/experience-notifications.md

Just a tiny code sample fix: added a missing parenthesis in the Roblox docs "Notification Permission Prompt Implementation" code sample.
The current Roblox docs code sample when copied directly would throw the following error, which is fixed by adding a parenthesis:
Roblox docs sample link containing the issue:
https://create.roblox.com/docs/cloud-services/experience-notifications#prompting-users-to-enable-notifications

added-missing-parenthesis

---

content/en-us/tutorials/fundamentals/coding-5/intro-to-dictionaries.md

Fixed spacing on "Intro to Dictionaries" page.

Fix spacing on "Intro to Dictionaries" page

---

content/en-us/reference/engine/classes/DataStore.yaml

Just spent half an hour trying to figure out why ListVersionsAsync wasn't returning anything ... turns out wiki doesn't properly specify the type of the parameter. Despite being named `minDate`, it takes an int64 of MILLISECONDS

Update param desc of DataStore:ListVersionsAsync

---

content/en-us/education/adventure-game-series/selling-items.md
content/en-us/luau/metatables.md
content/en-us/luau/scope.md
content/en-us/reference/engine/classes/HumanoidDescription.yaml
content/en-us/reference/engine/classes/Player.yaml
content/en-us/reference/engine/classes/StarterGui.yaml
content/en-us/reference/engine/classes/TestService.yaml
content/en-us/reference/engine/libraries/string.yaml
content/en-us/reference/engine/libraries/task.yaml
content/en-us/resources/the-mystery-of-duvall-drive/supporting-systems.md
content/en-us/scripting/scheduler.md
content/en-us/tutorials/fundamentals/coding-4/creating-a-timed-bridge.md

Removed extra space before defining function parameters

Remove extra space before defining function parameters

---

content/en-us/reference/engine/datatypes/RotationCurveKey.yaml

changed "type: number" to "type: CFrame"

fix RotationCurveKey.Value type in docs

---

content/en-us/production/monetization/immersive-ads.md

We typically get [dev forum reports/bugs](https://devforum.roblox.com/t/immersive-ads-not-enabled-for-games-with-over-2000-mau/3045190) stemming from confusion around how/when we calculate eligibility to publish ads. This change in text should help clarify our calculation mechanism.
[Slack thread](https://roblox.slack.com/archives/C06Q9288KBP/p1720462991946199) to arrive at updated text.

Correct text regarding eligibility calculation for ads publishing

---

content/en-us/reference/engine/classes/AnimationTrack.yaml

The current documentation for animation priorities lists the priorities in the following order:
1. Core (lowest priority)
2. Idle
3. Movement
4. Action
5. Action2
6. Action3
7. Action4 (highest priority)
However, this order is reversed compared to the actual Game Enum values where:
Updated:
1. Action4 (highest priority)
2. Action3
3. Action2
4. Action
5. Movement
6. Idle
7. Core (lowest priority)
This update ensures that the documentation accurately represents the actual priority levels used in the game, thereby preventing confusion for developers.

Corrected Priority Order for Animation States in Documentation

---

content/en-us/reference/engine/enums/SurfaceType.yaml

I made some changes to the Enum.SurfaceType documentation by either rephrasing some text, or adding some deprecation tags to defunct/discontinued items. The following changes are:
- Changing the word "side" to "surface" to refer to the specific surface (or surfaces) being used.
- Changing the phrasing to be read as past-tense.
- Adding a Deprecation message to Enum.SurfaceType itself as its original functionallity has been discontinued and has been largely replaced by newer methods.
https://devforum.roblox.com/t/1222218

(Enum.SurfaceType) rephrasing-and-deprecation-additions

---

content/en-us/reference/engine/classes/AudioFilter.yaml

The AudioFilter documentation states that a Q value of "sqrt(2), or 0.707 is flat" – but this 0.707 is sqrt(2) / 2

Update Documentation for AudioFilter

---

content/en-us/reference/engine/classes/StudioService.yaml

Previously, newActiveScript was used as a parameter, but GetPropertyChangedSignal does not accept parameters. As a result, newActiveScript was always nil, causing the script to fail. I have made newActiveScript a variable and I also added an existence check for ActiveScript.

Update StudioService.yaml (code example ActiveScript)

---

content/en-us/cloud/open-cloud/data-store-api-handling.md

The original alert info for the Input Validation section said "Perfect-Encoding", while the linked header is "Percent-Encoding". The commit changes "Perfect" into "Percent".

Minor typo in data-store-api-handling.md

---

content/en-us/cloud/open-cloud/usage-data-stores.md

In Data Stores reference, use `class.DataStore` instead of `class.GlobalDataStore`. 

Use DataStore instead of GlobalDataStore in reference

---

content/en-us/tutorials/building/effects/laser-traps-with-beams.md

Simply fixing the typo "Lasers Beams" such that it says "Laser Beams"

Fix typo: "Lasers Beams" -> "Laser Beams"

---

content/en-us/reference/engine/enums/ReverbType.yaml

Fixed grammar mistakes in the descriptions of `City` and `StoneCorridor`.
The description of `UnderWater` was also changed to be consistent with the others.

Fix Enum.ReverbType item descriptions

---

content/en-us/reference/engine/globals/RobloxGlobals.yaml
content/en-us/reference/engine/libraries/debug.yaml

Removes a broken reference to the deprecated and mostly obsolete DebuggerManager.

 Remove broken and deprecated reference to DebuggerManager

---

content/en-us/reference/engine/datatypes/RBXScriptSignal.yaml

Corrects a `RBXScriptSignal` to an `RBXScriptSignal`
This is consistent with the summaries for RBXScriptSignal properties.

Correct RBXScriptSignal grammar

---

content/en-us/reference/engine/enums/ForceLimitMode.yaml

Removed the additional whitespaces and the dot. This isn't visible on the website, however, I found it while using the Luau Language Server:

Fix punctuation in ForceLimitMode.yaml

---

content/en-us/studio/game-settings.md

Secrets can now be created and configured via the game settings security menu for local studio sessions. This requires that HTTP requests be allowed. 
https://devforum.roblox.com/t/secrets-store-general-availability/2892154/72

Add Secrets to game-settings.md

---

content/en-us/reference/engine/classes/AudioAnalyzer.yaml
content/en-us/reference/engine/classes/AudioChorus.yaml
content/en-us/reference/engine/classes/AudioCompressor.yaml
content/en-us/reference/engine/classes/AudioDeviceInput.yaml
content/en-us/reference/engine/classes/AudioDeviceOutput.yaml
content/en-us/reference/engine/classes/AudioDistortion.yaml
content/en-us/reference/engine/classes/AudioEcho.yaml
content/en-us/reference/engine/classes/AudioEmitter.yaml
content/en-us/reference/engine/classes/AudioEqualizer.yaml
content/en-us/reference/engine/classes/AudioFader.yaml
content/en-us/reference/engine/classes/AudioFilter.yaml
content/en-us/reference/engine/classes/AudioFlanger.yaml
content/en-us/reference/engine/classes/AudioListener.yaml
content/en-us/reference/engine/classes/AudioPitchShifter.yaml
content/en-us/reference/engine/classes/AudioPlayer.yaml
content/en-us/reference/engine/classes/AudioReverb.yaml

add descriptions for `AudioAnalyzer.SpectrumEnabled`, `Audio*.Bypass`, and `Audio*:GetConnectedWires`

add descriptions for SpectrumEnabled, Bypass, and GetConnectedWires

---

content/en-us/art/characters/facial-animation/creating-basic-heads.md

Update creating-basic-heads.md mapping instructions to include a specific example of the correct convention for custom property names that map frame number to FACS pose.
The specific "Frame#" format is only visible in the videos and gave me trouble the other day while trying to make poses with zero prior experience.

Update creating-basic-heads.md mapping instructions

---

content/en-us/reference/engine/classes/Tool.yaml

CFrames can now be edited from the property window, so this paragraph on Tool.Grip is invalid.

Remove "CFrame cant be edited" from Tool.yaml

---

content/en-us/luau/control-structures.md

Adds documentation for the `continue` keyword.
(does creator docs support the language mode `luau`, right now the sample is `lua`, as this has syntax highlighting for continue?)

Add `continue` keyword documentation

---

content/en-us/reference/engine/classes/PolicyService.yaml

Add documentation for IsContentSharingAllowed in PolicyService response, this field specifies whether content can be shared via the CaptureService:PromptShareCapture API (which currently supports sharing screenshots via share sheet on the users device).
https://devforum.roblox.com/t/captures-apis-are-now-available/2838188

Add documentation for IsContentSharingAllowed in PolicyService response

---

content/en-us/reference/engine/classes/GuiObject.yaml

There was just nothing in those 2 sections.
GuiObject.GuiState and GuiObject.Interactable now have short summaries and long descriptions of how they work.

Added missing sections: GuiState, Interactable

---

content/en-us/reference/engine/classes/AtmosphereSensor.yaml

Changed incorrect references to `AirDenstiy` in `reference/engine/classes/AtmosphereSensor.yaml` to `AirDensity`.

Fix "AirDenstiy" typo in AtmosphereSensor

---

content/en-us/reference/engine/libraries/task.yaml

- Fixes `task.defer` description that stated that it runs the code on the next resumption cycle. This is false. It runs at the end of the _current_ resumption cycle.
- Fixes `task.defer` and `task.spawn` inaccuracy that states they do not return anything. They both return a thread object, which is reflected in the return value section of the documentation. Thus, these sentences are removed.

Fix inaccuracies in spawn and defer descriptions.

---

content/en-us/reference/engine/classes/Part.yaml

- Make the table consistent with https://create.roblox.com/docs/reference/engine/enums/PartType
- Add details about exactness guarantees for part collisions

Add detailed documentation for Part.Shape

---

content/en-us/chat/bubble-chat.md

Adds info about using a `Script` with its `RunContext` set to `Client`, instead of just a `LocalScript`.

add info about runcontext to bubble chat docs

---

content/en-us/studio/beta.md

Removed "New Audio API" from Beta Features list.

Remove "New Audio API"

---

content/en-us/cloud/reference/oauth2.md

This PR adds some clarification on the OAuth2 resources endpoint response, where the endpoint may sometimes return a value of `U` in the `ids` list which is equivalent to the authorizing resource owner's ID.

Clarify resource owner `U` in OAuth2 reference

---

content/en-us/reference/engine/libraries/buffer.yaml

This pr fixes the integer number range for the value parameter in buffer.writeu16. Which is currently written as [0, 65536], where it should be [0, 65535]

Fix buffer.writeu16 int number range

---

content/en-us/reference/engine/datatypes/Random.yaml

math.random() explicitly mentions that exactly zero can be returned by reading it with basic number knowledge. However, Random:NextNumber() requires developers to know numerical range notation to determine that NextNumber can return exactly zero.
Apply the math.random() standard to Random:NextNumber().
[Found out about this in a hard way. Would like this post to be deleted due to me being embarassed by it](https://devforum.roblox.com/t/random-nextnumber-should-never-return-zero/3270962)

Random:NextNumber() clarifications

---

content/en-us/tutorials/curriculums/core/building/create-an-environment-with-terrain.md

Fixed it from saying "Set Base Size to 3" to saying "Set Brush Size to 3"
In Roblox Studio the terrain editor says brush size. The guide is saying to change the base size. I fixed the typo to say "Set Brush Size to 3"

Fixed another brush typo.md

---

content/en-us/studio/microprofiler/task-scheduler.md

Removes references of depreciated globals, and replaces references of them to their replacements in the task library.

Remove depreciated globals in task scheduler docs

---

content/en-us/reference/engine/classes/AdService.yaml

Edits AdsService to reference Immersive Ads
The link formatting might be broken here as I'm not 100% sure this links to the right guide.

Link AdService to Immersive Ads

---

content/en-us/chat/bubble-chat.md
content/en-us/education/build-it-play-it-mansion-of-wonder/adding-scripts.md
content/en-us/luau/enums.md
content/en-us/luau/type-coercion.md
content/en-us/performance-optimization/identifying.md
content/en-us/reference/engine/classes/Instance.yaml
content/en-us/reference/engine/classes/WeldConstraint.yaml
content/en-us/ui/frames.md

Changes some code examples to better fit good practices.

fix: updates code practices across the board

---

content/en-us/reference/engine/classes/Stats.yaml

Adds descriptions to the rest of the undocumented properties for the Stats service.

fix: update Stats.yaml

---

content/en-us/reference/engine/globals/LuaGlobals.yaml

Adds a note that xpcall's error handler preserves the stack of the erroring function.
This is useful to know if people are building error handlers and need to know the traceback.

Add note that xpcall's error handler preserves the trace

---

content/en-us/reference/engine/enums/TextTruncate.yaml

Added missing documentation and examples to Enum.TextTruncate
None:
AtEnd:
SplitWord:

TextTruncate example and SplitWord documented

---

content/en-us/reference/engine/globals/LuaGlobals.yaml

Error's Luau type def is `<T>(message: T, level: number): never`, not `(message: string, level: number): never`. It works as expected by throwing the passed object instead of a string. I haven't updated the summary text as this is (mostly) correct.

Fix error message type

---

content/en-us/education/battle-royale-series/cleanup-and-reset.md
content/en-us/education/battle-royale-series/creating-a-gui.md
content/en-us/education/battle-royale-series/ending-matches.md
content/en-us/luau/metatables.md
content/en-us/reference/engine/libraries/bit32.yaml
content/en-us/tutorials/use-case-tutorials/lighting/creating-flickering-lights.md
content/en-us/ui/3D-drag-detectors.md

Converts math.floor to the newer // operator which simplifies code and has improved performance.

Change math.floor to more performant // operator

---

content/en-us/cloud-services/memory-stores/hash-map.md

While working with MemoryStoreHashMap, I noticed there wasn't a direct link to its documentation. To improve accessibility, I added a link directly below the function explanations. This addition aims to make it easier for users to find detailed information, such as parameter descriptions, without having to search separately.

Add link to MemoryStoreHashMap documentation for easier access

---

content/en-us/reference/engine/datatypes/Instance.yaml

I made a simple change to the type of argument 'parent' in `Instance.new` from `Instance` to `Instance?` to accurately reflect that it is not required.

Modified type of argument parent in Instance.new constructor

---

content/en-us/reference/engine/classes/CollectionService.yaml
content/en-us/reference/engine/classes/Instance.yaml

This behavior can cause unexpected removal of tags added locally.

Warn about client-side tags being dropped

---

content/en-us/reference/engine/classes/BasePart.yaml

Since the various ApplyImpulse functions apply a "pure" impulse (resulting in an instantaneous change in velocity), using the word "force" is misleading. A force must be applied over some finite time span to produce a velocity change, whereas an impulse is applied instantaneously. This has led to confusion among developers.

Remove use of the word "force" in describing ApplyImpulse methods

---

content/en-us/projects/transferring-animations.md
content/en-us/resources/feature-packages/bundles.md

Some pages have pairs and ipairs creeping back in or that were missed in my previous PR for general iteration. This PR changes them to general iteration. Will update other pages in the future to further remove references to pairs and ipairs however that work is out of scope for this PR as it will be a larger change to the docs.

General Iteration #2

---

content/en-us/reference/engine/libraries/vector.yaml

The Luau team has recently developed and added to the [Luau documentation a new `vector` library](https://luau.org/library#vector-library), although this change has not been reflected into the Roblox Creator Documentation. To avoid potential confusion for developers who encounter a new undocumented library, I've decided to port the Luau `vector` documentation, with minimal changes (only omitting features not available in the Roblox environment such as 4-wide mode) to keep it concise and accurate to the Roblox environment.

Ported Luau documentation for vector library to the Roblox documentation

---

content/en-us/workspace/collisions.md

I've optimized the script for handling collision groups in Roblox. The main change involves removing the connection to DescendantAdded, applying the collision group immediately to all parts in the model upon character addition. This reduces unnecessary event connections, improving performance by applying the collision group once for all descendants, rather than repeatedly when new parts are added. This should help improve game performance, especially when handling many parts or players.

Optimization of Collision Group Script

---

content/en-us/studio/shortcuts.md

Fixed the inconsistent use of ctrl/⌘ shift and its order.

fix: shortcuts ctrl/command shift combination order

---

content/en-us/reference/engine/classes/AudioAnalyzer.yaml

Updates AudioAnalyzer docs to note that audio processing is disabled on the server

Update AudioAnalyzer docs to mention server limitations

---

content/en-us/reference/engine/classes/ChatWindowMessageProperties.yaml

Corrects the incorrect use of `Color3.new`

fix: TextColor3 default value

---

content/en-us/production/game-design/introduction-to-quest-design.md

- Corrected mis-attribution in screenshot from Adopt Me! to Pet Simulator X!

Correct mis-attributed game credit

---

content/en-us/scripting/attributes.md

This was changed in 653.
https://create.roblox.com/docs/en-us/release-notes/release-notes-653
> Instance.Changed and DataModel.ItemChanged signals will no longer be called when non-scriptable of inaccessible properties change.

Remove reference to .Changed firing for attribute changes

---

content/en-us/reference/engine/classes/AssetService.yaml
content/en-us/reference/engine/classes/EditableMesh.yaml

Changed one reference of "content" in EditableMesh.yaml to link to [the Content datatype](https://create.roblox.com/docs/reference/engine/datatypes/Content). Also added summaries for content parameters in AssetService.yaml to better explain what they are.
Credit to [@MrChickenRocket](https://devforum.roblox.com/u/MrChickenRocket) for making [the bug report here](https://devforum.roblox.com/t/feedback-on-editablemesh/3450653) asking for clarification on Content.

Update EditableMesh.yaml and AssetService.yaml

---

content/en-us/reference/engine/libraries/math.yaml

This PR updates the math documentation to include the definitions for the newly added `math.lerp` and `math.map`

Implement definitions for math.lerp and math.map

---

content/en-us/reference/engine/classes/HapticService.yaml

Change deprecation notice in HapticService to clarify that HapticEffect is not yet available, and set an alias so `Class.` is not visible but it will still link to `HapticEffect` when it is added.
Report: https://devforum.roblox.com/t/feedback-on-hapticservice/3466028/2

Clarify HapticEffect is not out on HapticService deprecation msg

---

content/en-us/cloud/open-cloud/usage-messaging.md

This pull request changes the link from https://www.authorize.roblox.com to the correct URL which is https://authorize.roblox.com

Change www.authorize.roblox.com to authorize.roblox.com

---

content/en-us/studio/microprofiler/task-scheduler.md

Removes an outdated bullet point regarding the use of `task.wait/task.spawn/task.delay`. It seems this is a holdover from the older global functions `wait/spawn/delay`, and that someone had simply added the `task` prefix to those older functions in this paragraph (you can see this was forgotten on the last reference to `spawn()`).
To the best of my understanding, the newer task library has no throttling issues like the older global functions, and thus the docs should not be recommending against their usage.
Relevant links:
- https://devforum.roblox.com/t/task-library-now-available/1387845
- https://create.roblox.com/docs/reference/engine/libraries/task

Remove outdated bullet point

---

content/en-us/chat/in-experience-text-chat.md

The method TextChatService:SendAsync() does not exist, it should be TextChannel:SendAsync()

Fix incorrect class in TextChatService overview

---

content/en-us/studio/microprofiler/tag-table.md

The tag as shown in MicroProfiler is "frameStep/SpatialFilter" not "frameStep/SpacialFilter".
I fixed the spelling.

Fix typo "Spacial" to "Spatial" in tag-table.md

---

content/en-us/chat/bubble-chat.md

In content/en-us/chat/bubble-chat.md, line 18 it should be 
`2. In the [Properties](../studio/properties.md) window, check the Class.BubbleChatConfiguration.Enabled checkbox.`
and not 
`2. In the [Properties](../studio/properties.md) window, check the Class.BubbleChatConfiguration.Enabled|Enabled checkbox.`

Unessesary word in bubble-chat.md

---

content/en-us/reference/engine/classes/TextChatMessageProperties.yaml

I was trying to figure out how to derive TextChatMessageProperites, and I couldn't find it anywhere. This PR aims to add a code snippet to the TextChatMessageProperties page ( https://create.roblox.com/docs/reference/engine/classes/TextChatMessageProperties ) that will show how to do so.

Added code snippet for deriving TextChatMessageProperties

---

content/en-us/reference/engine/classes/TextChannel.yaml

Elaborated on the sender/receiver structure of `TextChannel.ShouldDeliverCallback`. My co-worker got confused while he was working on a problem with us and thought the callback only gave you information about who sent the message, since in Play Solo you would be the only sender and recipient of the message. After confirming how I suspected it actually worked, I went in and made this documentation change so others hopefully don't have similar confusion in the future.

Clarity around the sender/receiver in ShouldDeliverCallback.

---

content/en-us/reference/engine/classes/DataModelMesh.yaml
content/en-us/reference/engine/classes/Lighting.yaml
content/en-us/reference/engine/classes/VideoService.yaml

Replaced "their are plans in the future" with "there are plans in the future" in the How to use Scale section. Also I fixed a misinformation stating that Lighting.Technology can be changed from Roblox Studio - it can't be even read from studio.

Replace their with there and mention that Lighting.Technology cannot be accessed from Roblox Studio

---

content/en-us/reference/engine/classes/VoiceChatService.yaml

EnableDefaultVoice didn't explain what it does when its set to false on a game that uses the new audio API.

Improve EnableDefaultVoice documentation

---

content/en-us/cloud/legacy.md
content/en-us/luau/type-checking.md

This PR adds documentation for the Asset Delivery API to the Legacy overview page. The new section includes the base URL, authentication types, and available endpoints with their corresponding scopes. 

Legacy API : asset-delivery api added

---

content/en-us/tutorials/fundamentals/coding-6/intro-to-module-scripts.md

to be specific, it says to create a ModuleScript in ServerStorage, but it is previously stated that they are commonly placed in ServerScriptService, so this fixes it
No links are needed, as the file and image right below the line I changed both state that it should be in ServerScriptService

Fix intro-to-module-scripts.md having a mixup

---

content/en-us/reference/engine/classes/Handles.yaml

I swapped the first two paragraphs in the `Handles` article to put the more general information first.

Improved reading flow by swapping first and second paragraph

---

content/en-us/luau/tables.md

* Removes reccomendation of `pairs()` and replaces it with generic iteration
* Renames the deepCopy function to deepClone
* Makes the deepClone function use table.clone
* Fix deepFreeze erroring if a value is already frozen
* Explains dot indexing for dictionaries `.key`
* Removes warning for using ipairs to iterate over a dictionary, as ipairs is unnessary to use unless wanting to stop at the first nil in a array with holes (a behavior that is very rarely desired)
The last one is a bit iffy so feel free to reverse it. Also unsure if the wording for `Write to dictionaries` is the best, but I think the added warning clears it up.

Update table docs

---

content/en-us/art/characters/creating/texturing-face.md
content/en-us/education/lesson-plans/roblox-developer-lesson.md

I have  fixed multiple typos, such as changing `A set of instructions can be e re-used in different parts of a script.` to `A set of instructions that can be re-used in different parts of a script.` and changing `.**30**` to `**0.300**`.

docs: fix multiple typos

---

content/en-us/reference/engine/classes/ContextActionService.yaml

- Document how the InputObject passed to a ContextActionService action function won't correspond to a bound input when the function is called with Cancel state.
- Since every entry in the table of function parameters would have an extra detail/note about it, it seemed unnecessary to keep those notes outside of the table, so they have been put in to the table.

Document InputObject behavior in CAS action functions

---

content/en-us/reference/engine/libraries/debug.yaml

Reverts Roblox/creator-docs#1085
The current system relies on those duplicates to render documentation for overloaded functions in the Script Editor. We know this isn't ideal, and we're looking into ways to improve how these duplicates are navigated and displayed on the docs site.
---
- Reverts #1085 to restore duplicate `debug.info()` entries in `debug.yaml` for correct overloaded function docs.
- Reintroduces detailed descriptions, parameters, code samples, and return types for `debug.traceback` and `debug.info`.
- Ensures documentation renders properly in the Script Editor with complete function overload information.

Revert "Removed duplicates of debug.info()"

---

content/en-us/reference/engine/datatypes/Enums.yaml

Enums page had a stray ')' character.

Tiny fix in Enums, stray ')' character

---

content/en-us/matchmaking/scoring.md
content/en-us/scripting/index.md

Fixes instances of “Roblox” that are misspelt as “Robox”, that is all!

Fix “Robox” Typos

---

content/en-us/luau/index.md

Fixes luau url pointing to https://luau-lang.org instead of https://luau.org

Fix luau url in luau docs

---

content/en-us/production/publishing/thumbnails.md

- Added respective references to the key binds for the camera tilting feature, which can be accessed by the `Z` and `C` keys while actively inside of freecam.

Add references to FreeCam camera tilting keybinds

---

content/en-us/reference/engine/classes/SocialService.yaml

This PR fixes two typos in the `options` parameters for PromptLinkSharing; `PreiviewDescription` and `PreviewAssettId`.

SocialService: Fix typos in PromptLinkSharing Parameters
