content/en-us/players/index.md
Some code here wasn't indented properly, so I've updated it to ensure it's easier to understand.
=> Minor code indentation fix

content/en-us/production/game-design/monetization-foundations.md
Fixed multiple grammar/spelling mistakes.
=> fix spelling and grammar errors in monetization-foundations

content/en-us/parts/solid-modeling.md
Changed "in quick sequence" to "in quick succession" as it is better terminology in this context.
=> Better word choice for solid-modeling.md

content/en-us/production/publishing/account-verification.md
Changed "Acccount" to "Account".
=> Typo Fix in account-verification.md

content/en-us/luau/functions.md
Replaced the deprecated delay() with task.delay().
=> Replace delay() with task.delay()

content/en-us/education/build-it-play-it-island-of-move/adding-animations.md
Replaced the deprecated Humanoid:LoadAnimation() with Animator:LoadAnimation().
=> Replace Humanoid:LoadAnimation() with Animator:LoadAnimation()

content/en-us/art/avatar/facial-animation/using-heads-in-studio.md, content/en-us/art/marketplace/intellectual-property.md, content/en-us/chat/legacy/admin-commands.md, content/en-us/education/adventure-game-series/finishing-the-project.md, content/en-us/education/build-it-play-it-create-and-destroy/icons-and-thumbnails.md, content/en-us/education/build-it-play-it-create-and-destroy/landing.md, content/en-us/education/lesson-plans/galactic-speedway-lesson.md, content/en-us/education/lesson-plans/intro-to-game-and-coding.md, content/en-us/education/support/private-servers-for-classroom-use.md, content/en-us/luau/operators.md, content/en-us/tutorials/fundamentals/coding-3/giving-points.md, content/en-us/tutorials/fundamentals/coding-5/making-changes-to-arrays.md, content/en-us/tutorials/scripting/basic-scripting/deadly-lava.md
Replaced 'a' with 'an' when it preceded a vowel sound.
=> Replace 'a' with 'an' when preceding a vowel sound.

content/en-us/education/build-it-play-it-island-of-move/adding-animations.md, content/en-us/production/earning-on-roblox.md, content/en-us/production/index.md, content/en-us/projects/assets/in-experience-asset-creation.md
- Added minor punctuation to [earning-on-roblox.md](https://github.com/Roblox/creator-docs/commit/4621802eb2d6dca486d7d34206c9132182fc1e2f)
- Removed dash for clarity at [index.md](https://github.com/Roblox/creator-docs/commit/bdd2e3eca203826db215dfd2c24fe33e6cb975a1)
- Improved wording at [index.md](https://github.com/Roblox/creator-docs/commit/ff58c53f897485561dbf0378f38d7401995dc133)
- Fixed typos and added missing references to [in-experience-asset-creation.md](https://github.com/Roblox/creator-docs/commit/7163572dc7a2c7ee41bddaff11bd02421fc6ea88)
- Updated example code in [adding-animations.md](https://github.com/Roblox/creator-docs/commit/d01422c96899d858597b9dd569cf17ea8ff6c431) to remove the use of deprecated methods
By submitting your pull request for review, you agree to the …
=> Fixed typos, added punctuation and rephrased certain sentences for clarity

content/en-us/scripting/multithreading.md
=> Grammar fixes for multithreading.md

content/en-us/education/battle-royale-series/cleanup-and-reset.md, content/en-us/education/battle-royale-series/coding-the-game-loop.md, content/en-us/education/battle-royale-series/creating-a-gui.md, content/en-us/education/battle-royale-series/ending-matches.md, content/en-us/education/battle-royale-series/managing-players.md, content/en-us/education/battle-royale-series/timers-and-events.md
Replaced the deprecated Players.NumPlayers with #Players:GetPlayers().
=> Replace Players.NumPlayers with #Players:GetPlayers()

content/en-us/scripting/scripts.md
Fixed a grammatical error that implied that ModuleScripts can only be used on either the server or client and not both.
=> Grammar fixes

content/en-us/characters/appearance.md
Replaced Players:GetChildren() with Players:GetPlayers(), added an indent for the line where we declare the humanoid variable, and created the HumanoidDescription inside the if statement so no memory is leaked if the character does not exist, or their humanoid does not exist.
=> Replace :GetChildren() with :GetPlayers(), add indent, and improve code

content/en-us/characters/emotes.md
Added an indent to all elements in emoteTable.
=> Add indents in emotes.md

content/en-us/players/avatar-context-menu.md, content/en-us/players/avatar-editor.md, content/en-us/players/avatar-inspect-menu.md, content/en-us/players/tools.md
Fixed indents for every page under Players.
=> Fix indents in Players

content/en-us/players/tools.md
Removed an unnecessary \ which caused a syntax error.
=> Fix code in tools.md

content/en-us/players/tools.md
Added syntax highlighting for LocalScripts and Scripts.
=> Add Syntax Highlighting in tools.md

content/en-us/chat/in-experience-text-chat.md
Performed a heavy amount of wordsmithing on the docs and brought the code samples up to speed (specifically: removing deprecated members, using better choices from available API and removing erroneous formatting).
=> Text chat wordsmithing

content/en-us/production/monetization/index.md
=> Minor Grammar fix

content/en-us/production/analytics/analytics-dashboard.md
=> Small Grammar fix for analytics-dashboard.md

content/en-us/luau/metatables.md
Fix the HTML in `/luau/metatables.md`. Follows up to #34 
=> fix: html in /luau/metatables.md

content/en-us/tutorials/core/scripting/script-an-upgrade-button.md
Making some changes to how we talk about the upgrade button.
=> adhoc Tutorial Improvements

content/en-us/scripting/scripts.md
Replaced ReplicateStorage with ReplicatedStorage.
=> Fix typos in scripts.md

content/en-us/ui/cross-platform-design.md
=> Fix typo in cross-platform-design.md

content/en-us/education/battle-royale-series/ending-matches.md
Added an auto-link for Player:LoadCharacter().
=> Add auto-link to ending-matches.md

content/en-us/education/battle-royale-series/finishing-the-project.md
=> Remove auto-link in finishing-the-project.md

content/en-us/parts/textures-decals.md
Corrected auto-links that did not lead to their specific property information.
=> Fix auto-links in texture-decals.md

content/en-us/scripting/data/player-data-purchasing.md
Added auto-links to several items that were missing them.
=> Add auto-links to player-data-purchasing.md

content/en-us/cloud-services/datastores.md
=> Add auto-link to datastores.md

content/en-us/production/promotion/invite-prompts.md
=> Add auto-link to invite-prompts.md

content/en-us/resources/modules/merch-booth.md
=> Add auto-link to merch-booth.md

content/en-us/projects/teleporting.md
Added auto-links to PlaceId and pcall.
=> Add auto-links to teleporting.md

content/en-us/production/localization/localizing-with-scripting.md
=> Add auto-link to localizing-with-scripting.md

content/en-us/ui/text-filtering.md
Added auto-links to several items that were missing them.
=> Add auto-links to text-filtering.md

content/en-us/tutorials/core/scripting/record-and-display-player-data.md
Replaced .FindFirstChild with :FindFirstChild() for better consistency and added missing auto-links.
=> Fix auto-links in record-and-display-player-data.md

content/en-us/production/publishing/account-verification.md
Replaced Player.IsVerified with Player:IsVerified() to communicate that :IsVerified() is a function and not a property.
=> Fix auto-link in account-verification.md

content/en-us/projects/data-model.md
Removed unnecessary text overrides and added missing auto-links.
=> Fix auto-links in data-model.md

content/en-us/tutorials/fundamentals/coding-6/intro-to-module-scripts.md
Added auto-links for require().
=> Add auto-links to intro-to-module-scripts.md

content/en-us/tutorials/scripting/input-and-camera/detecting-user-input.md
- Changed the wording regarding "user input" to be more consistent (and grammatically correct?)
=> Update detecting-user-input.md to have more consistent wording

content/en-us/scripting/services.md
Added auto-links for DataModel related functionality.
=> Add auto-links to services.md

content/en-us/tutorials/fundamentals/coding-1/creating-a-script.md, content/en-us/tutorials/fundamentals/coding-1/object-properties.md
Added missing auto-links and fixed several typos.
=> Fix auto-links and typos in coding-1

content/en-us/scripting/scripts.md
=> Add auto-links to scripts.md

content/en-us/production/roblox-user-base.md
Some small changes to the Roblox user base article.
• Removed 'O13' and 'U13.' They can be confusing and aren't found in any other article.
• Renamed Twitter to 'X,' but I don't care for it. It feels super clunky; feedback on that would be appreciated.
• Changed Dave Baszucki to David Baszucki. He generally seems to be called that more often, and it's the username of his [Roblox](https://www.roblox.com/users/24941) and [LinkedIn](https://www.linkedin.com/in/davidbaszucki) account.
If anyone knows what '5K' and '15mm' is meant to represent in the DAU distribution chart, please let me know. That doesn't make sense to me, and I imagine it's confusing to others as well.
=> User base article clarifications

content/en-us/studio/microprofiler/task-scheduler.md
Removed unnecessary text overrides, added missing auto-links, and fixed a typo.
=> Fix auto-links and a typo in task-scheduler.md

content/en-us/animation/inverse-kinematics.md
Removed unnecessary text overrides, added missing auto-links, and fixed several auto-links.
=> Fix auto-links in inverse-kinematics.md

content/en-us/tutorials/scripting/basic-scripting/scoring-points.md
Added auto-links to objects that were missing them.
=> Add auto-links to scoring-points.md

content/en-us/resources/modules/event-sequencer.md
=> Add auto-links to event-sequencer.md

content/en-us/tutorials/fundamentals/coding-1/creating-a-script.md, content/en-us/ui/text.md
=> Fix MD check failures

content/en-us/luau/strings.md
Adds basic string interpolation documentation. It's my first time writing new content to the documentation.
Question: Does the script parser support string interpolation?
=> Add String Interpolation to documentation

content/en-us/cloud-services/cross-server-messaging.md, content/en-us/education/battle-royale-series/finishing-the-project.md, content/en-us/scripting/data/player-data-purchasing.md, content/en-us/studio/microprofiler/tag-table.md, content/en-us/tutorials/fundamentals/coding-6/intro-to-module-scripts.md
Fixed a few typos.
'Realtime' is arguably a real word, but I added a space to maintain uniformity with other articles.
I considered changing 'games' to 'experiences' in finishing-the-project.md, but decided not to; doing so would require a lot of changes throughout the repo, and I wasn't even sure if it was the right move. If I get positive feedback on it, I'll create a new pull for it in the future.
=> Misspellings

content/en-us/cloud-services/memory-stores/index.md
Fixed grammar in the API Request Limits section, the title itself as well as the last sentence in the third paragraph.
=> Memory Store grammar fixes

content/en-us/production/monetization/developer-products.md
Added a space between to and download.
=> Add a space to developer-products.md

content/en-us/characters/pathfinding.md
Added missing end statements to pathfinding.md
=> Add missing end statements to pathfinding.md

content/en-us/studio/microprofiler/index.md
Added formatting improvements to shortcut and added a callout to 'Pause' button along the top bar in the micro profiler
=> Add formatting and pause button callout to microprofiler\index.md

content/en-us/sound/objects.md
Removed unnecessary backticks that caused links not to be highlighted properly, and fixed a link that led to the wrong page.
=> Fix links in objects.md

content/en-us/characters/r6-to-r15-adapter.md
=> Add auto-links to r6-to-r15-adapter.md

content/en-us/tutorials/fundamentals/coding-1/creating-a-script.md
Line 169 was missing concatenation between variable firstAnimal and " and "
Adding concatenation symbol ".." between the variable firstAnimal and " and ".
=> Update creating-a-script.md line 169

content/en-us/characters/pathfinding.md
Added missing end statement that had gone unnoticed to pathfinding.md 
=> Add missing end statement to pathfinding.md

content/en-us/production/promotion/experience-guidelines.md
Removing some info that's no longer accurate.
=> Experience Guidelines Fix

content/en-us/characters/appearance.md, content/en-us/education/resources/coding-concept-algorithms.md, content/en-us/tutorials/fundamentals/coding-6/coding-concept-algorithms.md
Fixes workspace typos and improves and matches loop usage in the coding concepts for algorithms.
=> Fix workspace typos and improve loops

content/en-us/workspace/streaming.md
Removes an unneeded ) character added by mistake in a recent pull request.
=> Remove unneeded )

content/en-us/education/adventure-game-series/code-the-leaderboard.md
Added a space between "." and "This", and properly formatted instructions. 
=> Fix grammar and formatting in code-the-leaderboard.md

STYLE.md
=> Update guidance around auto-links

content/en-us/production/game-design/balancing-virtual-economies.md
=> Update balancing-virtual-economies.md with spelling fix

content/en-us/tutorials/fundamentals/coding-2/multiple-parameters-and-arguments.md, content/en-us/tutorials/fundamentals/coding-2/parameters-practice-buttons.md, content/en-us/tutorials/fundamentals/coding-3/intro-to-if-statements.md, content/en-us/tutorials/fundamentals/coding-3/multiple-conditions.md
I fixed some comments on the coding fundamentals guide. Someone left ```lua capitalized so it did not work correctly.
- [X ] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [X ] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [X ] To the best of my knowledge, all proposed changes are accurate.
=> comment-fixes

content/en-us/production/publishing/console-guidelines.md
Improves service usage for UserInputService by using game:GetService() and a better variable name.
=> Improve service usage

content/en-us/players/avatar-editor.md
Replaced iterating over numbers to iterating over the array. Shortened character check.
=> Improve code in avatar-editor.md

content/en-us/tutorials/building/effects/laser-traps-with-beams.md
Removed an unnecessary `:FindFirstChild()`.
=> Improve code in laser-traps-with-beams.md

content/en-us/input/gamepad.md
Switched pairs to generalized iteration. Shortened character check. Removed nested if statements.
=> Improve code in gamepad.md

content/en-us/projects/performance-optimization/memory.md
I added a missing character in the word "the".
=> Fix missing character

content/en-us/studio/avatar-tab.md
Removed duplicated sentence:
> The **Accessory** section contains tools for creating layered or rigid [accessories](../art/accessories/index.md) from imported custom meshes.
=> Remove duplicate sentence

content/en-us/reference/engine/classes/PluginGui.yaml
Fix repeated `on` in PlayerGui
=> fix: repeated "on" in PlayerGui

README.md
Removes the coming soon note from API reference contributions since I'm pretty sure this is live now.
=> Remove coming soon note from README

content/en-us/projects/assets/in-experience-asset-creation.md
Added space. Replaced `.name` with `.Name`.
=> Improve code in in-experience-asset-creation.md

content/en-us/luau/type-checking.md
Added space. Removed unnecessary bracket.
=> Improve code in type-checking.md

content/en-us/reference/engine/classes/PluginAction.yaml
Changed non-existent method, `CreationPluginAction`, to correct method, `CreatePluginAction`.
=> Fixed typo in PluginAction.yaml

content/en-us/reference/engine/classes/ForceField.yaml
=> Typo in ForceField.yaml

content/en-us/production/publishing/vr-guidelines.md
Included reference to the new modes, and the 3rd person fixed camera setting.
=> Updated VR comfort settings documentation

content/en-us/reference/engine/classes/TextButton.yaml
Made increment value clearer. Replaced `wait` with `task.wait`. Made wait value clearer.
=> Improve code in TextButton.yaml

content/en-us/reference/engine/classes/TextBox.yaml
Made increment value clearer. Replaced `wait` with `task.wait`. Made wait value clearer.
=> Improve code in TextBox.yaml

content/en-us/reference/engine/classes/TextLabel.yaml
Made increment value more clear. Replaced `wait` with `task.wait`. Made wait value clearer.
=> Improve code in TextLabel.yaml

content/en-us/reference/engine/classes/AirController.yaml
Moved period outside of auto-link.
=> Fix auto-link in AirController.yaml

content/en-us/reference/engine/classes/SoundService.yaml
"with" -> "which": wrong word
"`Class.Sound`s" -> "`Class.Sound`'s": plural to possessive
- [ x] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [x ] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [ x] To the best of my knowledge, all proposed changes are accurate.
=> Grammatical errors

content/en-us/reference/engine/classes/ChorusSoundEffect.yaml, content/en-us/reference/engine/classes/CompressorSoundEffect.yaml, content/en-us/reference/engine/classes/DistortionSoundEffect.yaml, content/en-us/reference/engine/classes/EchoSoundEffect.yaml, content/en-us/reference/engine/classes/EqualizerSoundEffect.yaml, content/en-us/reference/engine/classes/FlangeSoundEffect.yaml, content/en-us/reference/engine/classes/PitchShiftSoundEffect.yaml, content/en-us/reference/engine/classes/ReverbSoundEffect.yaml
Adds summaries to CompressorSoundEffect, ChorusSoundEffect, DistortionSoundEffect, EchoSoundEffect, EqualizerSoundEffect, FlangeSoundEffect, PitchShiftSoundEffect, and ReverbSoundEffect
- [ X ] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [ X ] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [ X ] To the best of my knowledge, all proposed changes are accurate.
=> Add summaries to SoundEffect classes

content/en-us/reference/engine/enums/ListenerType.yaml
Adds summaries and description for the `ListenerType` enum.
- [ X ] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [ X ] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [ X ] To the best of my knowledge, all proposed changes are accurate.
=> Add documentation for ListenerType

content/en-us/scripting/events/remote.md
- Replaced the example of inherent communication between server and clients:
-> Since the default character movement is client-authoritative, with client being the network owner, the current example could be misleading.
- Switched pairs with generalized iteration.
=> Apply a minor update to remote.md

content/en-us/education/battle-royale-series/timers-and-events.md
Small change this time to update an example from coroutines to task library. Since task library immediately resumes I'd image it being a better example for a timer.
https://devforum.roblox.com/t/task-library-now-available/1387845
=> Update example to task library.

content/en-us/reference/engine/classes/Instance.yaml
This pull request simply just adds a notice that FindFirstDescendant is disabled, currently the only way to know this is to find out the hard way.
=> Add notice about FindFirstDescendant being disabled

content/en-us/tutorials/gameplay-scripting/detecting-hits.md
Replaced `Class.[...]` with `Datatype.[...]`. Replaced `CFrame.new(pos, lookAt)` with `CFrame.lookAt(pos, lookAt)`.
=> Fix auto-links and improve code in detecting-hits.md

content/en-us/reference/engine/classes/StudioTheme.yaml
Removed an extraneous code block that was interfering with an example.
=> Fix snippet formatting in StudioTheme.yaml

content/en-us/reference/engine/enums/TeleportResult.yaml
Fixes grammar on teleport result page.
=> Fix grammar

content/en-us/chat/legacy/admin-commands.md, content/en-us/chat/legacy/legacy-chat-system.md, content/en-us/education/battle-royale-series/cleanup-and-reset.md, content/en-us/education/battle-royale-series/landing.md, content/en-us/education/battle-royale-series/project-setup.md, content/en-us/education/battle-royale-series/timers-and-events.md, content/en-us/education/build-it-play-it-create-and-destroy/icons-and-thumbnails.md, content/en-us/education/build-it-play-it-island-of-move/designing-poses.md, content/en-us/education/build-it-play-it-island-of-move/landing.md, content/en-us/education/build-it-play-it-mansion-of-wonder/connect-the-beam.md, content/en-us/education/collaboration/collaboration-best-practices.md, content/en-us/education/developer/beta-testing-experiences.md, content/en-us/education/resources/coding-concept-algorithms.md, content/en-us/education/resources/collaboration-best-practices.md, content/en-us/education/resources/intro-to-digital-safety.md, content/en-us/luau/type-checking.md, content/en-us/parts/materials.md, content/en-us/production/game-design/liveops-essentials.md, content/en-us/production/game-design/season-pass-design.md, content/en-us/projects/assets/manager.md, content/en-us/projects/performance-optimization/memory.md, content/en-us/scripting/index.md, content/en-us/tutorials/core/scripting/script-game-behavior.md, content/en-us/tutorials/environmental-art/assemble-an-asset-library.md, content/en-us/tutorials/environmental-art/greybox-your-environment.md, content/en-us/tutorials/fundamentals/coding-3/giving-points.md, content/en-us/tutorials/fundamentals/coding-6/coding-concept-algorithms.md
```
admin-commands.md
legacy-chat-system.md
cleanup-and-reset.md
battle-royale-series / landing.md
build-it-play-it-island-of-move / landing.md
project-setup.md
timers-and-events.md
icons-and-thumbnails.md
designing-poses.md
connect-the-beam.md
collaboration / collaboration-best-practices.md
resources / collaboration-best-practices.md
beta-testing-experiences.md
resources / coding-concept-algorithms.md
coding-6 / coding-concept-algorithms.md
intro-to-digital-safety.md
type-checking.md
materials.md
liveops-essentials.md
season-pass-design.md
manager.md
memory.md
index.md
script-game-behavior.md
assemble-an-asset-library.md
greybox-your-environment.md
giving-points.md
```
=> bulk edits

content/en-us/scripting/multithreading.md
- Fixed the original sample by defering the generation part.
-> The original script started sending messages before the workers ran. Now it defers till the next cycle and all the scripts are ready by the time.
- Modified some comments for clarity.
- Minor changes that retain the same functionality.
- Rewritten the explanation paragraph in a more 'neutral' language.
=> Update terrain generation sample in multithreading.md

content/en-us/workspace/streaming.md
Replaced "persitent" with "persistent".
=> Fix typo in streaming.md

content/en-us/reference/engine/enums/GuiState.yaml
Adds summaries to the GuiState enum
=> Add summaries to GuiState

content/en-us/tutorials/scripting/intermediate-scripting/hit-detection-with-lasers.md
Fix typo containing vulgar language
=> Fix typo containing vulgar language

content/en-us/reference/engine/globals/RobloxGlobals.yaml
The description for "require" was very short and should provide more context on its behavior, especially regarding one of the major uses of modulescripts, that is to have a method of sharing values across scripts. Also does not elaborate on client server boundary affecting require
=> Update require RobloxGlobals.yaml

content/en-us/reference/engine/classes/CollectionService.yaml
Added summaries and descriptions for previously-undocumented CollectionService TagAdded and TagRemoved events.
=> Document CollectionService.TagAdded and CollectionService.TagRemoved

content/en-us/reference/engine/classes/Player.yaml
Fixed a function call in CharacterRemoving code snippet
Issue location: https://create.roblox.com/docs/pt-br/reference/engine/classes/Player#CharacterRemoving
=> fix Player.yaml

content/en-us/reference/engine/classes/HumanoidDescription.yaml
=> Update HumanoidDescription.yaml typo

content/en-us/luau/luau-csharp-comparison.md
Need to declare variables
Declare variables as local in Luau or string in C#
=> Fix syntax issues in example

content/en-us/reference/engine/classes/Player.yaml
1. Code sample:
Changed the original sample to reflect the described good practice in retrieving freshly spawned characters in local scripts in StarterGui and StarterPack.
Side note: Player.Character still referencing the old character is more common with immediate signal behaviour. I didn't notice this in deferred mode.
2. Shortened the last paragraph and revised grammar. Switched the word "deleted" with "replaced", because old characters are not locally destroyed (yet?).
Inspired by: https://devforum.roblox.com/t/psa-playercharacter-or-playercharacteraddedwait-to-get-a-character-model-from-a-tool-is-no-bueno/2857165
=> Update Player.Character in Player.yaml

content/en-us/luau/queues.md
removed invisible characters from [queues.md](https://create.roblox.com/docs/en-us/luau/queues)
=> remove invisible characters from queues.md

content/en-us/education/support/creating-bundled-installers.md
Corrected typo "this can difficult" to "this can be difficult"
=> Correct grammar in creating-bundled-installers.md

content/en-us/reference/engine/classes/PolicyService.yaml
=> ADHOC: Update PolicyService.yaml

content/en-us/platform.md
=> Update platform.md footnote

content/en-us/parts/terrain.md
=> Add note for Shorelines upgrade

content/en-us/art/accessories/index.md
"Hats" was mistakenly spelled as "chats".
=> Fix typo in Accessories page

content/en-us/reference/engine/enums/BodyPartR15.yaml, content/en-us/reference/engine/libraries/table.yaml
=> Fix typos in table.yaml, BodyPartR15.yaml

content/en-us/production/promotion/ads-manager.md
=> broken table fixed in ads-manager.md

content/en-us/education/resources/roblox-educators.md, content/en-us/production/promotion/experience-guidelines.md
=> Update to Türkiye

content/en-us/luau/functions.md
This PR fixes a code sample that uses the wrong string function to convert a series of numbers representing bytes into a string. The current, incorrect, version calls `string.byte` which does not return anything when called with only numbers. The fixed version calls `string.char` which correctly returns "secret" here as indicated by the original comment.
=> Fix code sample for variadics

content/en-us/reference/engine/libraries/table.yaml
Updates table.sort description to be clearer about how to create a valid comparison function. This question comes up often enough I think it is worth updating the documentation.
=> Updates table.sort description to be clearer

content/en-us/input/mobile.md
fixed a weird line from the CAS button section
=> Fix the grammar here

content/en-us/reference/engine/classes/GroupService.yaml, content/en-us/reference/engine/classes/StarterGui.yaml, content/en-us/reference/engine/classes/TextLabel.yaml, content/en-us/reference/engine/classes/TextService.yaml
Fixed typos and adjusted formatting to increase clarity & consistency.
=> Fix typos and clarify formatting

STYLE.md
Removing some code brackets which do not look intended after a period. I believe this does not need any sources as I just noticed it while skimming through the document.
=> Minor formatting fix in STYLE.md

content/en-us/luau/control-structures.md
Fixed control structures page code formatting
=> Fix control structures page code formatting

content/en-us/scripting/scripts.md
Fixed missing ) in scripts.md, which caused a syntax error
=> Fix missing ) in scripts.md

content/en-us/luau/scope.md, content/en-us/reference/engine/classes/GuiBase2d.yaml, content/en-us/reference/engine/classes/WorldRoot.yaml, content/en-us/ui/positioning-and-sizing.md
=> Fix spelling of descendant

content/en-us/scripting/multithreading.md
Fixed parenting before setting properties, which is bad practice.
=> Fix not parenting last

content/en-us/cloud-services/memory-stores/best-practices.md, content/en-us/reference/engine/classes/Lighting.yaml, content/en-us/tutorials/fundamentals/coding-3/multiple-conditions.md, content/en-us/tutorials/fundamentals/coding-4/nested-loops.md
Replaced var = var + 1 with var += 1
=> Use compound addition assignment operator

content/en-us/reference/engine/classes/UserInputService.yaml, content/en-us/reference/engine/classes/VRService.yaml, content/en-us/resources/beyond-the-dark/user-interface.md, content/en-us/tutorials/fundamentals/coding-4/nested-loops.md
- [Renamed serverStorage to ServerStorage](https://github.com/Roblox/creator-docs/commit/c3112890b2612f4b3a8074489042113e710460fd)
- [Renamed userInputService to UserInputService](https://github.com/Roblox/creator-docs/commit/c2c9a324e3ca8c24fcb3f86aa15f8dd128eddb79)
- [Renamed tweenService to TweenService](https://github.com/Roblox/creator-docs/commit/dc8f9707e6b400e1000ad26c159de3363c82c7fb)
=> Use PascalCase variables for services

content/en-us/resources/the-mystery-of-duvall-drive/developing-a-moving-world.md
=> Removed unnecessary brackets

content/en-us/tutorials/fundamentals/coding-4/nested-loops.md
Removed an invisible character in code, which caused a syntax error.
=> Remove invisible character

content/en-us/tutorials/fundamentals/coding-3/giving-points.md, content/en-us/tutorials/fundamentals/coding-3/powerups-with-if-statements.md
Added missing spacing in local declaration
=> Add missing spacing in local declaration

content/en-us/education/battle-royale-series/cleanup-and-reset.md
=> Fix misplaced `

content/en-us/cloud-services/memory-stores/best-practices.md
- Renamed memoryStore variable to MemoryStoreService
- Used `game:GetService("Players"):GetPlayers()` instead of `game.Players:GetChildren()`
- Remove use of `pairs`
- Used `count // 4` instead of `math.floor(count / 4)`
- Use tabs instead of spaces and correct the indentation
=> Improve memory store best practices page

content/en-us/tutorials/fundamentals/coding-5/making-changes-to-arrays.md
=> Note that table.find exists

content/en-us/education/battle-royale-series/cleanup-and-reset.md, content/en-us/education/battle-royale-series/creating-a-gui.md, content/en-us/education/battle-royale-series/ending-matches.md, content/en-us/education/battle-royale-series/managing-players.md
Used table.remove return value.
=> Use table.remove return value

STYLE.md
=> Fix typo and grammar in style guide

content/en-us/reference/engine/classes/Actor.yaml
=> Link methods on Actor page

content/en-us/studio/microprofiler/task-scheduler.md
Corrected RunServer to RunService.
=> Correct RunServer to RunService

content/en-us/scripting/scripts.md
Removed incorrect statement that modules can not return nil.
=> Correct module return information

content/en-us/cloud-services/memory-stores/hash-map.md
- Fixed invalid `=`
- Fixed missing `end`
- Used tab instead of space
=> MemoryStore hashmap page improvements

content/en-us/education/battle-royale-series/ending-matches.md, content/en-us/tutorials/fundamentals/coding-5/pairs-and-ipairs.md
Removed unicode characters that appear like spaces but cause a syntax error.
=> Fix broken space

content/en-us/projects/assets/api.md
Replaced \`\`\`lua with \`\`\`json for json text
=> Fix lua instead of json

content/en-us/chat/legacy/admin-commands.md
Fixed syntax errors on legacy admin commands page
=> Fix syntax errors

content/en-us/luau/metatables.md, content/en-us/projects/teleporting.md, content/en-us/scripting/scripts.md
Removed/replaced all unnecessary semicolons
=> Remove unnecessary semicolons

content/en-us/education/build-it-play-it-galactic-speedway/main-page.md
=> Fix spelling of millennia

content/en-us/production/game-design/prototyping.md
=> Fix spelling of limitations

content/en-us/education/build-it-play-it-create-and-destroy/snap-to-grid.md
=> Fix spelling of palette

content/en-us/art/characters/facial-animation/moods.md, content/en-us/characters/appearance.md, content/en-us/characters/name-health-display.md, content/en-us/chat/bubble-chat.md, content/en-us/chat/in-experience-text-chat.md, content/en-us/players/avatar-inspect-menu.md, content/en-us/reference/engine/classes/Camera.yaml, content/en-us/reference/engine/classes/Humanoid.yaml, content/en-us/resources/beyond-the-dark/custom-characters.md, content/en-us/tutorials/core/scripting/script-an-upgrade-button.md, content/en-us/tutorials/gameplay-scripting/detecting-hits.md, content/en-us/tutorials/scripting/intermediate-scripting/hit-detection-with-lasers.md
- Replaced `FindFirstChildOfClass("Humanoid")` with `FindFirstChildWhichIsA("Humanoid")`, which respects inheritance
- Replaced `FindFirstChild("Humanoid")` with `FindFirstChildWhichIsA("Humanoid")`, so that it works with a renamed humanoid
=> Use FindFirstChildWhichIsA to find humanoid

content/en-us/tutorials/scripting/basic-scripting/intro-to-scripting.md
=> Fix . instead of ,

content/en-us/ui/text-filtering.md
Changed "filteredTextResult' in text-filtering.md to "filteredText" to match the rest of the given example.
=> Changed filteredTextResult to filteredText to match example

content/en-us/art/overview-dcc.md, content/en-us/environment/index.md, content/en-us/production/game-design/season-pass-design.md
`softwares` -> `software`
`ligthing` -> `lighting`
`quicky` -> `quickly`
=> Fix spelling

content/en-us/cloud/open-cloud/oauth2-develop.md
Replace the undefined "verifier" variable use with "code_verifier" that was meant to be there. 
=> Fix variable name in oauth2-develop.md

content/en-us/reference/engine/classes/Model.yaml
=> Clarify the availability of the ModelStreamingMode property

content/en-us/production/publishing/badges.md
Fixed using wrong variable name.
=> Fix using wrong variable name

content/en-us/tutorials/3D-art/creating-elevators.md
Use elseif instead of else + if
=> Use proper syntax for elseif

content/en-us/production/publishing/dmca-guidelines.md
- Corrected the location of more information about the Roblox DMCA Process
Previously, users were directed to Section 5 of the Roblox Terms of Service. However, the fifth section is actually about payments and refunds. I corrected it to Section 6, which is about Intellectual Property and UGC that covers these topics.
=> DMCAGuidelinesUpdate

content/en-us/cloud-services/data-stores/player-data-purchasing.md, content/en-us/cloud-services/memory-stores/best-practices.md, content/en-us/education/build-it-play-it-island-of-move/adding-animations.md, content/en-us/players/avatar-editor.md, content/en-us/production/promotion/invite-prompts.md, content/en-us/reference/engine/libraries/os.yaml, content/en-us/studio/microprofiler/index.md
Renamed unused for loop variables to _
=> Unused for loop variables

content/en-us/animation/events.md, content/en-us/chat/legacy/server-side-chat-modules.md, content/en-us/education/adventure-game-series/finishing-the-project.md, content/en-us/education/battle-royale-series/finishing-the-project.md, content/en-us/education/build-it-play-it-create-and-destroy/change-the-script.md, content/en-us/luau/functions.md, content/en-us/luau/tuples.md, content/en-us/players/tools.md, content/en-us/resources/the-mystery-of-duvall-drive/developing-a-moving-world.md, content/en-us/scripting/scheduler.md, content/en-us/tutorials/building/effects/laser-traps-with-beams.md, content/en-us/tutorials/building/effects/using-particles-for-explosions.md, content/en-us/tutorials/building/environments/in-game-sounds.md, content/en-us/tutorials/building/ui/interactive-buttons.md, content/en-us/tutorials/core/scripting/script-game-behavior.md, content/en-us/tutorials/fundamentals/coding-2/parameters-practice-buttons.md, content/en-us/tutorials/fundamentals/coding-3/giving-points.md, content/en-us/tutorials/fundamentals/coding-3/intro-to-if-statements.md, content/en-us/tutorials/fundamentals/coding-3/powerups-with-if-statements.md, content/en-us/tutorials/fundamentals/coding-4/intro-to-for-loops.md, content/en-us/tutorials/fundamentals/coding-4/repeating-code-with-while-loops.md, content/en-us/tutorials/fundamentals/coding-5/intro-to-dictionaries.md, content/en-us/tutorials/fundamentals/coding-5/making-changes-to-arrays.md, content/en-us/tutorials/fundamentals/coding-6/coding-concept-algorithms.md, content/en-us/tutorials/fundamentals/coding-6/intro-to-module-scripts.md, content/en-us/ui/layout-and-appearance.md
- Indent with tabs instead of spaces
- Removed unnecessary spaces
- Fixed intro-to-dictionaries enemy table example
=> Whitespace improvements

content/en-us/reference/engine/classes/Mouse.yaml
Undo change to 10,000. It's a bug and should be 1,000.
=> Change back to 1,000

content/en-us/performance-optimization/designing.md
The statement about anchoring and collision properties on parts isn't totally accurate. There are no "unnecessary" physics calculations. Parts that are not being interacted with will fall asleep, and not do any work. Same goes for the notes about collision.
The "Improving" page already covers this same information, with more detail, and predicated with how a developer could determine when they need to optimize simulation. This approach is much preferred when it comes to physics simulation.
=> Remove physics point from designing.md

content/en-us/cloud-services/data-stores/player-data-purchasing.md, content/en-us/education/battle-royale-series/managing-players.md, content/en-us/education/battle-royale-series/timers-and-events.md, content/en-us/education/build-it-play-it-island-of-move/adding-animations.md, content/en-us/education/resources/coding-concept-algorithms.md, content/en-us/includes/engine-comparisons/fishing-pole-code-sample.md, content/en-us/input/mobile.md, content/en-us/luau/comments.md, content/en-us/resources/beyond-the-dark/custom-characters.md, content/en-us/tutorials/core/scripting/create-player-hazards.md, content/en-us/tutorials/fundamentals/coding-5/pairs-and-ipairs.md, content/en-us/tutorials/scripting/intermediate-scripting/creating-player-tools.md, content/en-us/tutorials/scripting/intermediate-scripting/saving-data.md
- Indent with tabs instead of spaces
- Removed unnecessary spaces
=> More spacing improvements

content/en-us/scripting/module.md
- Tabs instead of spaces
- Commas instead of semicolons
- Generalised iteration instead of next
=> Improve module.md

content/en-us/reference/engine/classes/Humanoid.yaml, content/en-us/reference/engine/classes/InsertService.yaml, content/en-us/reference/engine/classes/Lighting.yaml, content/en-us/reference/engine/classes/LocalizationTable.yaml, content/en-us/reference/engine/classes/PlayerGui.yaml, content/en-us/reference/engine/classes/Players.yaml, content/en-us/reference/engine/classes/ProximityPromptService.yaml, content/en-us/reference/engine/classes/TeleportService.yaml, content/en-us/reference/engine/classes/Tool.yaml, content/en-us/reference/engine/classes/UserInputService.yaml, content/en-us/reference/engine/classes/VRService.yaml, content/en-us/reference/engine/classes/VoiceChatService.yaml, content/en-us/reference/engine/libraries/task.yaml
=> Formatting improvements

content/en-us/luau/type-coercion.md
- Added "Pi is" prefix to the comments for clarity.
Updated the comments in the documentation to accurately reflect the output of the print statements.
=> Updated the comments in the documentation to accurately reflect the output.

content/en-us/art/characters/facial-animation/moods.md, content/en-us/characters/appearance.md, content/en-us/education/adventure-game-series/selling-items.md, content/en-us/tutorials/fundamentals/coding-2/coding-a-function.md, content/en-us/tutorials/fundamentals/coding-5/returning-values-from-tables.md, content/en-us/tutorials/fundamentals/coding-6/creating-with-module-scripts.md, content/en-us/tutorials/scripting/input-and-camera/detecting-user-input.md, content/en-us/tutorials/scripting/intermediate-scripting/creating-a-health-pickup.md, content/en-us/tutorials/scripting/intermediate-scripting/hit-detection-with-lasers.md
=> More formatting improvements

content/en-us/parts/materials.md
Update of the Clay Roof Tiles Asset IDs in accordance with the new texture updates we've done for this material.
=> Update AssetIDs for Clay Roof Tiles in materials.md

content/en-us/reference/engine/globals/RobloxGlobals.yaml
I added some deprecation messages to the "Roblox Globals" Documentation for some methods that have been replaced. This is to add further context as to why they are replaced, and to further direct readers to the newer methods.
I have none, its mostly for convinience to the reader.
=> deprecation-message-additions

content/en-us/projects/assets/api.md
moved 'CreatorType' parameter up to improve documentation clarity.
=> reorder parameters for clarity

content/en-us/reference/engine/globals/LuaGlobals.yaml
This pull request improves wording for the global function `select`. A sentence with the same meaning is also removed.
=> Improve wording for select()

content/en-us/reference/engine/classes/WrapLayer.yaml
Clarify puffiness range being between -1 to 1.
=> Clarify puffiness range being between -1 to 1

content/en-us/reference/engine/classes/Animator.yaml
Change AnimationTracks|AnimationTracks to Class.AnimationTrack|AnimationTracks
=> change AnimationTracks to Class.AnimationTrack

content/en-us/ui/labels.md
Update labels.md.  "insert a ScreenGui." -> "insert a SurfaceGui."
=> Update labels.md, fix error text

content/en-us/production/analytics/custom-events.md
Long hyphen was typed when commenting at line 49, when a normal hyphen was expected. Also removed the useless newline.
there when commenting at line 49, when a normal hyphen was expected.
=> Fix Code Error.md

content/en-us/reference/engine/datatypes/Axes.yaml
Remove self link from Axes class
=> Remove self link from Axes

content/en-us/reference/engine/classes/TextChannel.yaml
=> Update TextChannel API reference to highlight new channel tabs feature

content/en-us/tutorials/curriculums/core/building/create-an-environment-with-terrain.md
Changed Text from incorrectly saying to "Set Base Size to 18" to "Set Brush Size to 18".
=> Fixed typo

content/en-us/reference/engine/classes/TweenService.yaml
Adds documentation for the newly added `TweenService:SmoothDamp` method.
=> fix: add SmoothDamp documentation

content/en-us/tutorials/fundamentals/coding-1/creating-a-script.md
Removed the "s" in creating-a-script.md on line 115
Before the change: "Bad Variables Names"
After the change: "Bad Variable Names"
=> In creating-a-script.md, the extra s on line 115 was unnecessary

content/en-us/studio/ui-overview.md
Fixes a typo on line 254, 'emultation', to 'emulation'
=> 'emultation' to 'emulation'

content/en-us/cloud/open-cloud/oauth2-registration.md
=> Fix typo in oauth2-registration.md

content/en-us/production/localization/automatic-translations.md
Add Arabic to list of automatic translation-supported languages; change formatting for Chinese to match what we have on other parts of platform
Add Arabic to list of automatic translation-supported languages; change formatting for Chinese to match what we have on other parts of platform
=> Update automatic translation languages

content/en-us/tutorials/use-case-tutorials/animation/play-character-animations.md
summarised in commit message. there is no end on the function in the code snippet.
- [ x] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [x ] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [x ] To the best of my knowledge, all proposed changes are accurate.
=> Fix code snippet on "Play character animations" page

content/en-us/reference/cloud/assets/v1.json
Update the description of OC Assets GetAsset() endpoint
=> ADHOC: updates docs for OC Assets API

content/en-us/reference/engine/classes/AudioPlayer.yaml, content/en-us/reference/engine/classes/AudioTextToSpeech.yaml
These are both live but it looks like the documentation was never filled in for them.
=> Update documentation for GetWaveformAsync

content/en-us/reference/engine/classes/PackageLink.yaml
Fixed typo 'would allows' to 'would allow'
=> Fix spell issue

tools/checks/utils/allowedHttpLinks.txt
=> ADHOC: Update allowedHttpLinks.txt

content/en-us/tutorials/fundamentals/coding-6/create-with-module-scripts.md
Removed code discrepancy, in the for loop, between documentation and script from the project.
Fixed Destroy function to remove the model correctly.
=> chest-destroy-function
